### ISSUE TITLE
Markers

### ISSUE THREAD

**Issue by SagarDhiman018** [zyzdev/flutter_street_view#1]
Hi author, Thanks for the package, Can i put markers in street view with this package? If yes, please let me know the steps. 
Thanks in advance.

**Comment by zyzdev** [comment]
@SagarDhiman018 No, the flutter_google_street_view  plugin not support adding marker.

Is the feature 'put markers in street view' like [this](https://developers.google.com/maps/documentation/ios-sdk/streetview#markers_within_street_view)?

**Comment by zyzdev** [comment]
Close this issue here.
Version 2.2.0, add feature `putting marker to street view`, but **iOS only**.
Because this feature was supported on [Maps SDK for iOS](https://developers.google.com/maps/documentation/ios-sdk/streetview#markers_within_street_view).

**Comment by poqueque** [comment]
Are there any plans to implement this feature for [Android](https://developers.google.com/maps/documentation/android-sdk/streetview)

**Comment by zyzdev** [comment]
> Are there any plans to implement Markers for Android? It looks it's also supported [Maps SDK for Android](https://developers.google.com/maps/documentation/android-sdk/streetview)

I didn't find any intruduction of adding marker to street view for android.([Maps SDK for Android](https://developers.google.com/maps/documentation/android-sdk/streetview))
Could you tell me the chapter?

**Comment by danPyk** [comment]
Are there any chances to implement web markers? https://developers.google.com/maps/documentation/javascript/custom-markers?hl=pl Thanks for the plugin.
