### ISSUE TITLE
Feature request: Add listener for location/pan/zoom changes

### ISSUE THREAD

**Issue by chaeMil** [zyzdev/flutter_street_view#11]
Hey thanks for the awesome work! I would really appreciate if you consider adding listeners for location, pan and zoom changes. Thanks! :) Keep up the good work!

**Comment by zyzdev** [comment]
Hi chaeMil, 
Callback onCameraChangeListener and onPanoramaChangeListener meet your request.
See demo `Street View Panorama events(demo/street_view_panorama_events.dart)` in `example` for usage.
<img title="Android" src="https://user-images.githubusercontent.com/16483162/152174768-073a7a02-e9de-40fb-aee0-68f07e7f4d89.png" width="300" />
