### ISSUE TITLE
Street View Side-By-Side 

### ISSUE THREAD

**Issue by adnanefouam** [zyzdev/flutter_street_view#12]
Can i display the Street View panorama alongside a map with a marker that displays the current position of the panorama on the map ?

<img width="855" alt="Screenshot 2022-02-23 at 05 05 36" src="https://user-images.githubusercontent.com/59290932/155260132-5a838265-37fd-4647-af3d-573fffed923c.png">

**Comment by zyzdev** [comment]
Callback onPanoramaChangeListener provide the position of current panorama.
And you can use the position to move the marker on the map.
See demo `Street View Panorama events(demo/street_view_panorama_events.dart)` in `example` for usage.
<img title="Android" src="https://user-images.githubusercontent.com/16483162/152174768-073a7a02-e9de-40fb-aee0-68f07e7f4d89.png" width="300" />
