### ISSUE TITLE
Does this package reuse panorama object to reduce instantiation count?

### ISSUE THREAD

**Issue by cantaspinar** [zyzdev/flutter_street_view#16]
A dynamic Street View panorama is charged for each instantiation of a panorama object. 
According to Google docs, an instantiation of a panorama object occurs:

On Android, with one of [StreetViewPanoramaFragment, SupportStreetViewPanoramaFragment, or StreetViewPanoramaView](https://developers.google.com/maps/documentation/android-sdk/streetview) classes. A panorama is counted each time the related onCreate() method is called.

On iOS, with the [GMSPanoramaView](https://developers.google.com/maps/documentation/ios-sdk/streetview) object.

I wanted to ask if using FlutterGoogleStreetView widget creates a panoroma object every time or reuses the first one.

**Comment by zyzdev** [comment]
I have good news for you!
v3.0.0 add reusing feature to reduce the count of instantiation panorama.
Try it.
