### ISSUE TITLE
Inside ListView Animating StreetView Camera Up & Down is hard

### ISSUE THREAD

**Issue by Aristidios** [zyzdev/flutter_street_view#18]
Hello 👋,

First of all thanks for your package it's great,

I'm having issues when using `FlutterGoogleStreetView()` inside a `ListView` as the scrolling of the vertical `ListView` conflicts with the gesture to moveCamera Up & Down on touch devices - any ideas how to solve this ?

Also the _Google Maps credits titles_ move up & down while scrolling

**Comment by zyzdev** [comment]
[IgnorePointer](https://api.flutter.dev/flutter/widgets/IgnorePointer-class.html) may helpful.
You should decide which widget(ListView or FlutterGoogleStreetView) can consume the touch event.

**Comment by Aristidios** [comment]
@zyzdev Thanks for you answer, the thing is FlutterGoogleStreetView is a child of ListView therefore [IgnorePointer](https://api.flutter.dev/flutter/widgets/IgnorePointer-class.html) will also prevent touch events on FlutterGoogleStreetView :/

**Comment by zyzdev** [comment]
@Aristidios Try feeding gestureRecognizers
```Dart
FlutterGoogleStreetView(
 ...
   gestureRecognizers: <Factory<OneSequenceGestureRecognizer>>{
       Factory<OneSequenceGestureRecognizer>(
          () => EagerGestureRecognizer(),
      ),
   },
...
)
```

**Comment by zyzdev** [comment]
Feeding gestureRecognizers like below should solve this issue.

```Dart
FlutterGoogleStreetView(
 ...
   gestureRecognizers: <Factory<OneSequenceGestureRecognizer>>{
       Factory<OneSequenceGestureRecognizer>(
          () => EagerGestureRecognizer(),
      ),
   },
...
)
```
