### ISSUE TITLE
Error on location no available, throwed in web 

### ISSUE THREAD

**Issue by lautarozanuttini** [zyzdev/flutter_street_view#21]
Hi zyzdev, great package by the way, I've an issue throwing on web platform of flutter and its when location its not available. I saw the page where you show how to fix it but nothing, its keep crashing, I will attached images of that error. Thanks.
![Screenshot 2022-10-19 171411](https://user-images.githubusercontent.com/79458253/196828970-41bf00ba-4275-49bd-a56f-a7409f0ece32.png)
![Screenshot 2022-10-19 171430](https://user-images.githubusercontent.com/79458253/196828973-e886f71c-8a40-45b6-b12a-d66d511a6c13.png)

**Comment by zyzdev** [comment]
Hi @lautarozanuttini,

In my opinion, the problem is `onPanoramaChangeListener` didn't receive exception when feeding invalid `initPos` or `initPanoId` to `FlutterGoogleStreetView`.
It's a bug. 
Version [[3.1.2-dev.1](https://pub.dev/packages/flutter_google_street_view/versions/3.1.2-dev.1)] fix it and you can try it.
`example/street_view_panorama_events.dart` may help you testing it.

Thanks.

**Comment by lautarozanuttini** [comment]
Hi zyzdev, first thanks a lot for your help,  i am testing now but still the issue with version 3.1.2-dev.1
here is the error.
![Screenshot 2022-10-20 154648](https://user-images.githubusercontent.com/79458253/197032348-a84ff17c-bc42-4291-830b-8271aaf367b9.png)

**Comment by zyzdev** [comment]
Hi lautarozanuttini,

The exception was thrown by plugin [google_maps](https://pub.dev/packages/google_maps), function `Future<StreetViewResponse> getPanorama`.
Change return type of `getPanorama` to `Future<StreetViewResponse?>` can solve the exception.

`flutter_google_street_view` depend on `google_maps` to implement web platform.

For plugin `flutter_google_street_view`, this exception is meaning the location is `no panorama available`, and will throw exception at `onPanoramaChangeListener` to `notice user` the location is no panorama available.

The exception should report to [google_maps issues](https://github.com/a14n/dart-google-maps/issues) if it make a problem to your work.

**Comment by lautarozanuttini** [comment]
Hi zyzdev, perfect! im going to do that now and report this to google_maps, thank you a lot.
