### ISSUE TITLE
Component not loading in web release mode

### ISSUE THREAD

**Issue by allebarrosm** [zyzdev/flutter_street_view#23]
Hello, I use the dependency only for the web and open the street view when I press the button, in debug mode it shows correctly and does not present any problems, but in release mode it does not load anything.

I check my google key, and it's ok. I try the dependency examples with my key and have the same issue on release.

**Debug mode**

![Captura de Tela 2023-03-27 às 11 10 41](https://user-images.githubusercontent.com/110492225/227965381-130aafca-25bd-4e5d-ae22-d2ad5cc3c264.png)

**Release mode**

![Captura de Tela 2023-03-27 às 11 01 52](https://user-images.githubusercontent.com/110492225/227965446-ad00bf47-6e6a-4741-970b-103da3cbf462.png)

**Comment by zyzdev** [comment]
Hi allebarrosm,

v3.1.3 fixed this bug, try it.

**Comment by allebarrosm** [comment]
> 
It's working now, thanks!!
