### ISSUE TITLE
Throw Exception unknown in onPanoramaChangeListener 

### ISSUE THREAD

**Issue by Santi92** [zyzdev/flutter_street_view#6]
Hi 

It happens that I am dealing with the errors in the `onPanoramaChangeListener`, but currently it is throwing an unknown error and I want to know why it occurs, since it is different from the most common one which is `Exception: Oops ..., no valid panorama found with position: -45.1313, 151.214123`

## Message

 **Exception: setPosition, catch unknown error.**
 
<img width="929" alt="Screen Shot 2021-11-26 at 3 05 17 PM" src="https://user-images.githubusercontent.com/12769042/143625862-9b8ee6ae-0aa4-4952-a303-62834559391c.png">

Attached the location to replicate the error

### :::LATITUDE:::

4.6544114

### :::LONGITUDE:::

-74.1229244

**Comment by zyzdev** [comment]
Bug fixed.
Please update to version 2.2.3
Close issue here.


![Screenshot_1639023220](https://user-images.githubusercontent.com/16483162/145333268-b59fa1a2-a025-4dd7-ad38-6678865a0d5b.png)
