### ISSUE TITLE
Taking screenshot of FlutterGoogleStreetView

### ISSUE THREAD

**Issue by siraj-logicvalley** [zyzdev/flutter_street_view#8]
how to take the screenshot of FlutterGoogleStreetView?

**Comment by zyzdev** [comment]
flutter_street_view cares about providing streev view api in flutter only.

You should implement it by yourself. 
FlutterGoogleStreetView is widget. To implement it, [the discuss from stackoverflow](https://stackoverflow.com/questions/51117958/how-to-take-a-screenshot-of-the-current-widget-flutter) may helpful.
