### ISSUE TITLE
Street view keep loading ios

### ISSUE THREAD

**Issue by adnanefouam** [zyzdev/flutter_street_view#9]
my streetView section keep loading 
<img width="638" alt="Screenshot 2022-01-04 at 12 22 17" src="https://user-images.githubusercontent.com/59290932/148052128-9e3f7dc7-c595-4e3b-9c94-8fe1138dfbdc.png">

` FlutterGoogleStreetView(
          initSource: StreetViewSource.outdoor,
          initBearing: 30,
          initTilt: 30,
          initZoom: 1.5,
          initPos: LatLng(-45.125783, 151.276417),
        )`

**Comment by zyzdev** [comment]
LatLng(-45.125783, 151.276417) is no valid panorama. 
The callback `onPanoramaChangeListener` will receive exception and you can decide what is next.
See demo `Street View Panorama events(demo/street_view_panorama_events.dart)` in `example` for usage.
